#!/bin/sh
# **********************************************************************
#
# Copyright (c) 2002
# IONA Technologies, Inc.
# Waltham, MA, USA
#
# All Rights Reserved
#
# **********************************************************************

#
# Try to find top-level directory
#
if test -f ob/src/com/ooc/CORBA/ORB.java
then
    top_srcdir=ob
elif test -f src/com/ooc/CORBA/ORB.java
then
    top_srcdir=.
elif test -f ../src/com/ooc/CORBA/ORB.java
then
    top_srcdir=..
elif test -f ../../src/com/ooc/CORBA/ORB.java
then
    top_srcdir=../..
elif test -f ../../../src/com/ooc/CORBA/ORB.java
then
    top_srcdir=../../..
elif test -f ../../../../src/com/ooc/CORBA/ORB.java
then
    top_srcdir=../../../..
else
    $echo "$0: can't find top-level directory"
    exit
fi

#
# Run standard init script
#
. $top_srcdir/../config/sh.init

#
# Set Java CLASSPATH
#
CLASSPATH="$top_srcdir/demo/hello0/classes${SEPARATOR}$CLASSPATH"
CLASSPATH="$top_srcdir/lib${SEPARATOR}$CLASSPATH"
export CLASSPATH

#
# Set Java boot classpath
#
java_version=`$JAVA -version 2>&1`
if `$echo $java_version | grep '1\.[456]' > /dev/null`
then
    JAVA="$JAVA -Djava.endorsed.dirs=$top_srcdir/lib"
fi

#
# The name of reference file
#
ref=Hello.ref

#
# Function to deactivate the server
#
repid=0
srvid=0
deactivate()
{
    if test $srvid -ne 0
    then
        kill $srvid
    fi

    exit
}
trap deactivate 1 2 3 4 5 6 7 8 10 12 13 14 15

#
# Start server
#
$echo
$echo "Waiting for server to start up... \c"
rm -f $ref
$JAVA hello.Server &
srvid=$!
count=0
while test ! -s $ref -a $count -lt 6
do
    sleep 1
    count=`expr $count + 1`
done
if test ! -s $ref
then
    $echo "Failed!"
    $echo "(Server was not started)"
    exit
else
    $echo "OK!"
fi
 
#
# Start client
#
$echo
#$echo "h\nh\nh\nx" | 
$JAVA hello.Client

#
# Deactivate everything
#
deactivate
